appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: jlptf25IuWsCOrXeaeeG1sBnzjUNYOEVkE5Pd1Mqa1I9MKztX8IX4FDLr+60R2DOFuSF76u4D5jI4hyA4GMd9zIE5+OHlCwvZAVPZQj5IDNkt4z5yKv15IjgvxxxkAAfQ14OH9RamCKpSMUWJpAhsJ4hMdUxw+2wZguP7+NcEo5jPt1qN41imjtS7kXZTPIfn7YQL8gh2JLp8iIk5hYEZhF64LLdtyIIJyVZlOg28xMTSYVq6OZaW1vSwcEGOGvJdNV+GcbxKu4Ark1nI3HtNYMrI1iQuKrkuyu8F4PuNEvgGQHGar+rky1gIo6WC6dP+EtzDNy8zUn6boSKFSBMYq1TsVCBz4smOB8OHJOU0RYHcDHpcuYPFZKEVqiVx4RJvI043SVuSUG4G09CyvDhtIzldLzSS8sD4HwIijVCM7jiihdxY65rS8CMIkPQJcM7ir59NxQO2hO8/yaQWM6gVu146zHHObYptacRqLfcK1ZK2KISptjXqNI4+/py0S57/vxladbERDuOWj/4dq7tU7JuxcLnB43oxj/tBznd6bcKmEXt2I6AqX/t3BwngE8rFeWZOj6F5HRyPqN/B6XMGszVf1150DD0FAFnuvSE6VXx27YCUzeai/7VVTPoC0XqpwMC2l/V1dQvaRkMDg5QeFbTiBdUkYecY833c9CP998=}
